name: Build and Test

on:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  test:
    name: Build and Test

    strategy:
      matrix:
        target:
          - id: 'linux-amd64'
            os: 'ubuntu-18.04'
          - id: 'darwin-amd64'
            os: 'macos-latest'
          - id: 'windows-amd64'
            os: 'windows-latest'
        go: [1.14]
      fail-fast: true

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set up just
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install just

      - name: Run all the tests
        shell: bash
        run: |
          just test

      - name: Run all the examples
        shell: bash
        run: |
          just examples
# Skipped for now because of Github banning the API request from actions.
# You can find more info in this PR: https://github.com/wasmerio/wasmer-go/pull/118#issuecomment-588487544
#       - name: Test bazel build
#         shell: bash
#         run: |
#           export GOOS=$(go env GOHOSTOS)
#           curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-${GOOS}-amd64"
#           mkdir -p "${GITHUB_WORKSPACE}/bin/"
#           mv "bazelisk-${GOOS}-amd64" "${GITHUB_WORKSPACE}/bin/bazel"
#           chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
#           "${GITHUB_WORKSPACE}/bin/bazel" build //...
